#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp.

# Check if all required parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    # Disable strict host key checking for scp and transfer the file
    if scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/; then
        echo "File transferred successfully."
    else
        echo "Error transferring file."
    fi
fi
