#!/usr/bin/env bash
# Configures the Nginx server to have a custom 404 page that
# contains the string Ceci n'est pas une page.

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
err_page="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $err_page" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload

