#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu server with a custom 404 page

# Display message for updating and installing Nginx
echo -e "Updating and installing Nginx...\n"
sudo apt-get update -y -qq
sudo apt-get install nginx -y

# Display message for setting up minor configurations
echo -e "\nSetting up some minor configurations...\n"

# Start Nginx service
sudo service nginx start

# Allow Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Display message for backing up default index
echo -e "Backing up the default index file...\n"
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Display message for creating a new index file
echo -e "Creating a new index file with 'Hello World!'...\n"
echo -e "Hello World!" | sudo dd status=none of=/var/www/html/index.nginx-debian.html

# Configure redirection for /redirect_me (as per previous script)
echo -e "\nConfiguring redirection for /redirect_me...\n"
sudo bash -c "cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL"

# Configure custom 404 page
echo -e "\nConfiguring custom 404 page...\n"
sudo bash -c "cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
        echo 'Ceci n'\''est pas une page';
    }
}
EOL"

# Restart Nginx
sudo service nginx restart

# Display completion message
echo -e '\nNginx installation, configuration, and custom 404 page setup completed successfully. ✅\n'
