#!/usr/bin/env bash
# This script configures web-02 to be identical to web-01 and adds a custom Nginx response header

# Install Nginx if not already installed
install_nginx() {
    command -v nginx &>/dev/null
    if [ $? -ne 0 ]; then
        echo "Installing Nginx..."
        sudo apt-get update -y -qq && sudo apt-get install -y nginx -qq
        echo "Nginx installed."
    else
        echo "Nginx is already installed."
    fi
}

# Function to configure Nginx with custom header
configure_nginx() {
    echo "Configuring Nginx with custom header..."
    server_config="server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        add_header X-Served-By \$hostname;
        location / {
            try_files \$uri \$uri/ =404;
        }
        error_page 404 /error_404.html;
        location = /error_404.html {
            internal;
        }
    }"

    echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
    echo "Nginx configured with custom header."
}

# Start or restart Nginx
start_or_restart_nginx() {
    if pgrep -x "nginx" >/dev/null; then
        echo "Restarting Nginx..."
        sudo service nginx restart
    else
        echo "Starting Nginx..."
        sudo service nginx start
    fi
    echo "Nginx started/restarted."
}

# Main function
main() {
    install_nginx
    configure_nginx
    start_or_restart_nginx
    echo "Web-02 configured and Nginx running."
}

main
