#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server


echo -e "Updating and checking necessary files...\n"

# Function to install a given package
function install() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "${1} is already installed.\n"
    fi
}
# Install HAProxy
install haproxy

echo -e "\nSetting other dependencies.\n"

# Backup the default HAProxy server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Define the HAProxy server configuration
server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend cletsymedia-tech-frontend
    bind *:80
    default_backend cletsymedia-tech-backend

backend cletsymedia-tech-backend
    balance roundrobin
    server 422289-web-01 3.85.41.2:80 check
    server 422289-web-02 34.229.55.147:80 check
"

# Apply the HAProxy server configuration
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by the init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "configured - Roundrobin On web-01 & web-02"

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
