#!/usr/bin/env bash
# Bash script to install and configure HAProxy on lb-01 server

# Function to install HAProxy
install_haproxy() {
    if ! command -v haproxy &>/dev/null; then
        echo "Installing HAProxy..."
        sudo apt-get update -y -qq && sudo apt-get install -y haproxy -qq
        echo "HAProxy installed."
    else
        echo "HAProxy is already installed."
    fi
}

# Function to configure HAProxy
configure_haproxy() {
    echo "Configuring HAProxy..."
    sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 422289-web-01 3.85.41.2:80 check
    server 422289-web-02 34.229.55.147:80 check
EOF'
    echo "HAProxy configured."
}

# Function to restart HAProxy
restart_haproxy() {
    echo "Restarting HAProxy..."
    sudo systemctl restart haproxy
    echo "HAProxy restarted."
}

# Main function
main() {
    install_haproxy
    configure_haproxy
    restart_haproxy
    echo "HAProxy installation and configuration completed successfully."
}

main
