#!/usr/bin/env bash
# fix short and sweet.
# sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
# pkill -1 nginx

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
