#!/usr/bin/env bash
#Script that displays list of curr running processes
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Use ps command to display process information in a user-oriented format
ps -axjf | head -50 | awk '{printf "%-10s %6s %4s %4s %6s %6s %-6s %4s %6s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}'
