#!/usr/bin/env bash
# start, stop, restart process script

pid_file="/var/run/my_process.pid"

start() {
    if [ -f "$pid_file" ]; then
        echo "manage_my_process is already running."
    else
        sudo ./manage_my_process &
        echo $! > "$pid_file"
        echo "manage_my_process started"
    fi
}

stop() {
    if [ -f "$pid_file" ]; then
        pid=$(cat "$pid_file")
        sudo kill "$pid"
        rm "$pid_file"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
