#!/usr/bin/env bash
# Read /etc/passwd using while loop and IFS
while IFS=':' read -r username x uid gid info home shell; do
    # Display the user information in the specified format
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $x, more info about the user here: $info"
done < /etc/passwd