#!/usr/bin/env bash
# Looping from 1 - 10
# the 4th iteration should display "bad luck"
# the 8th iteration should display "good luck"
# Display "Best School" for the remainder of the iteration
i=1;
while [ $i -le 10 ]
do
if [ $i -eq 4 ];
then
echo "bad luck"
elif [ $i -eq 8 ];
then
echo "good luck"
else
echo "Best School"
fi
((i++))
done
