#!/usr/bin/env bash
# Use while loop & case to display nums from 1-20
# display 4 and then "bad luck from China" for 4th iteration
# display 9 and then "bad luck from Japan" for 9th iteration
# display 17 and then "bad luck from Italy" for 17th iteration
i=1;
while [ $i -le 20 ]; do
  case $i in
  4) echo $i
  echo "bad luck from China"
  ;;
  9) echo $i
  echo "bad luck from Japan"
  ;;
  17) echo $i
  echo "bad luck from Italy"
  ;;
  *)
  echo $i
  esac
  ((i++))
done
