#!/usr/bin/env bash
# Display information about the file 'school'
# Whether the file exists or not and is it a regular file

if [ -e 'school' ]; then
    echo 'school file exists'
    
    if [ -s 'school' ]; then
        echo 'school file is not empty'
    else
        echo 'school file is empty'
    fi

    if [ -f 'school' ]; then
        echo 'school is a regular file'
    fi
else
    echo 'school file does not exist'
fi
