#!/bin/bash
# This script sets up a basic firewall configuration using UFW (Uncomplicated Firewall)

# Deny all incoming connections by default
sudo ufw default deny incoming

# Allow all outgoing connections by default
sudo ufw default allow outgoing

# Allow incoming connections on port 80 (HTTP)
sudo ufw allow 80/tcp

# Allow incoming connections on port 443 (HTTPS)
sudo ufw allow 443/tcp

# Allow incoming connections on port 22 (SSH)
sudo ufw allow 22/tcp

# Enable the UFW firewall with the configured rules
sudo ufw enable

echo -e "Process Completed.\n"
