#!/usr/bin/env bash
# Update the hosts file
cp /etc/hosts ~/hosts.new

# Add an entry for facebook.com
sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
