#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

# Change permissions of nginx.conf
chmod 644 /etc/nginx/nginx.conf

# Update nginx.conf to run as nginx user
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf

# Update default site to listen on port 8080
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default

# Stop Apache2 service
pkill apache2

# Restart Nginx service
su nginx -s /bin/bash -c 'service nginx restart'
